# 应用名称
spring:
  application:
    name: ImageUpload
  # 应用服务 WEB 访问端口
server:
  port: 8088

file:
  upload:
#    path: F:\System\workspace\files\
#    path: /root/to/files
     path: /var/www/html/backend/files/